---
abstract: 'Utilities for Using/Traversing Gentoo Repositories'
author:
  - 'Kent Fredric <kentfredric@gmail.com>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gentoo-Repository
no_index:
  directory:
    - inc
    - t
requires:
  Best: 0.11
  Gentoo::Util: 0.01
  Iterator: 1.04
  Iterator::IO: 0.02
  Iterator::Util: 0.02
  MooosX::Declare: 0.03
  Moose: 0.63
  Moose::Util::TypeConstraints: 0.63
  MooseX::Method::Signatures: 0.06
  perl: 5.01
  version: 0.76
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
